modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
modId="schematicon"
version="1.0.0"
displayName="Schematicon"
description="A creative chess-styled dimension with isolated inventory."

[[dependencies.schematicon]]
modId="neoforge"
type="required"
versionRange="[21.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.schematicon]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.22)"
ordering="NONE"
side="BOTH"

[[mixins]]
config="schematicon.mixins.json"
