modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
modId="schematicon"
version="1.0.0"
displayName="Schematicon"
description="A creative planning dimension for builders. Switch from survival to creative and back with fully separate inventories and no balance disruption."
logoFile="logo.png"
authors="Baphy404"

[[mods.contacts]]
sources="https://github.com/Troll-Bonnie/ChessDim-1.21.1"

[[dependencies.schematicon]]
modId="neoforge"
type="required"
versionRange="[21.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.schematicon]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.22)"
ordering="NONE"
side="BOTH"

[[mixins]]
config="schematicon.mixins.json"
